config/routes.rb
Rails.application.routes.draw do
  scope "/auth" do
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  end
  
  get '/login', to: redirect('auth/users/sign_in')
  get '/lpr' => 'home#landing_page_redirect'

  get 'v' => 'audience_votes#new', as: :new_audience_vote
  post 'v' => 'audience_votes#create', as: :create_audience_vote
  get 'v/thankyou' => 'audience_votes#thankyou', as: :audience_vote_thankyou

  get 'orders/new'
  post 'orders/create'
  get 'orders/confirm_email'
  get 'orders/print_tickets'
  get 'orders/thankyou'
  get 'orders/verify_email'

  get 'settings' => 'settings#modify'
  post 'settings' => 'settings#update', as: :update_settings

  get 'home/index'
  resources :participants do
    collection do
      post 'update_order'
    end
  end
  resources :ticket_orders do
    collection do
      post 'admission_fee_paid'
    end
  end
  resources :tickets, only: [:index, :destroy] do
    collection do
      get 'print_tickets'
      post 'batch_create'
      get 'ticket_inspection'
      post 'checkin'
    end
    member do
      get 'image'
    end
  end
  resources :votes, only: :index
  resources :jurors, only: [:create, :update, :destroy]

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/participant.rb
class Participant < ApplicationRecord
    has_many :votes, dependent: :destroy
    has_many :jurors, dependent: :nullify

    has_attached_file :picture

    validates :name, presence: true
    validates_attachment :picture, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  load_and_authorize_resource

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.order(:position)
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Die TeilnehmerIn(en) wurden erstellt.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Die TeilnehmerIn(en) wurden aktualisiert.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Die TeilnehmerIn(en) wurden gelöscht.' }
      format.json { head :no_content }
    end
  end

  def update_order
    params[:participant_ids].each_with_index do |participant_id, position|
      Participant.find(participant_id).try(:update_attribute, :position, position)
    end
  end

  protected
    def set_active_item
      @active = :participants
    end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name, :description, :yt_video_id, :picture)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= simple_form_for(@participant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: "Name" %>
    <%= f.input :description, label: "Beschreibung der Vorführung" %>
    <%= f.input :picture, as: :file, label: "Bild" %>
    <%= f.input :yt_video_id, label: "YouTube-Video-ID" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Speichern", class: "btn-primary" %>
  </div>
<% end %>

app/views/participants/_video.html.erb
<% if participant.yt_video_id.present? %>
    <div class="videoWrapper">
        <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/<%= participant.yt_video_id %>?rel=0" frameborder="0" allowfullscreen></iframe>
    </div>
<% else %>
    kein Video verfügbar
<% end %>

app/views/participants/edit.html.erb
<h2>TeilnehmerIn bearbeiten</h2>

<%= render 'form', participant: @participant %>

app/views/participants/index.html.erb
<table class="table table-striped table-with-actions">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>YT-Video-ID</th>
      <th>
        <%= new_button new_participant_path %>
      </th>
    </tr>
  </thead>

  <tbody id="participants" data-update-order-href="<%= update_order_participants_path %>">
    <% @participants.each do |participant| %>
      <tr data-id="<%= participant.id %>">
        <td><%= participant.name %></td>
        <td><%= truncate participant.description %></td>
        <td><%= participant.yt_video_id %></td>
        <td>
          <%= details_button participant %>
          <%= edit_button edit_participant_path(participant) %>
          <%= destroy_button participant %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/participants/new.html.erb
<h2>TeilnehmerIn eintragen</h2>

<%= render 'form', participant: @participant %>

app/views/participants/show.html.erb
<table class="table table-striped">
  <tr>
    <td>Name:</td>
    <td><%= @participant.name %></td>
  </tr>
  <tr>
    <td>Beschreibung:</td>
    <td><%= @participant.description %></td>
  </tr>
</table>

<hr />

<div class="row">
  <div class="col-sm-6">
    <%= image_tag @participant.picture.url, style: "max-width: 80%;" %>
  </div>
  <div class="col-sm-6">
    <%= render "video", participant: @participant %>
  </div>
</div>