config/routes.rb
Rails.application.routes.draw do
  scope "/auth" do
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  end
  
  get '/login', to: redirect('auth/users/sign_in')
  get '/lpr' => 'home#landing_page_redirect'

  get 'v' => 'audience_votes#new', as: :new_audience_vote
  post 'v' => 'audience_votes#create', as: :create_audience_vote
  get 'v/thankyou' => 'audience_votes#thankyou', as: :audience_vote_thankyou

  get 'orders/new'
  post 'orders/create'
  get 'orders/confirm_email'
  get 'orders/print_tickets'
  get 'orders/thankyou'
  get 'orders/verify_email'

  get 'settings' => 'settings#modify'
  post 'settings' => 'settings#update', as: :update_settings

  get 'home/index'
  resources :participants do
    collection do
      post 'update_order'
    end
  end
  resources :ticket_orders do
    collection do
      post 'admission_fee_paid'
    end
  end
  resources :tickets, only: [:index, :destroy] do
    collection do
      get 'print_tickets'
      post 'batch_create'
      get 'ticket_inspection'
      post 'checkin'
    end
    member do
      get 'image'
    end
  end
  resources :votes, only: :index
  resources :jurors, only: [:create, :update, :destroy]

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    has_many :votes, dependent: :destroy
    belongs_to :ticket_order, optional: true
    scope :online_tickets, -> { where.not(ticket_order_id: nil) }
    scope :offline_tickets, -> { where(ticket_order_id: nil) }

    before_create :set_code

    def set_code
        characters = ('A'..'Z').to_a + ('a'..'z').to_a + ('0'..'9').to_a
        begin
            self.code = (0...5).map { characters.sample(random: SecureRandom) }.join
        end while Ticket.find_by(code: code).present?
        true
    end
end

app/models/ticket_order.rb
class TicketOrder < ApplicationRecord
    has_many :tickets, dependent: :destroy

    before_create :set_email_verification_token

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :number_of_tickets, presence: true
    validates :email, presence: true, format: { with: Devise.email_regexp }    

    def set_email_verification_token
        begin
            self.email_verification_token = SecureRandom.hex
        end while TicketOrder.find_by(email_verification_token: email_verification_token).present?
        true
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  include ApplicationHelper
  load_and_authorize_resource

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.order(created_at: :desc)
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Das Ticket wurde gelöscht.' }
      format.json { head :no_content }
    end
  end

  def print_tickets
    if params[:ticket_ids].blank? || !params[:ticket_ids].is_a?(Array)
      render nothing: true
    else
      @tickets = params[:ticket_ids].map { |id| Ticket.find(id) }
    end
  end

  def image
    ticket = Ticket.find(params[:id])
    if ticket
      send_data TicketGenerator.generate_ticket_jpeg(ticket), :type => "image/jpeg", :disposition => "inline"
    else
      render nothing: true
    end
  end

  def batch_create
    if is_number?(params[:amount]) 
      tickets = []
      params[:amount].to_i.times { tickets << Ticket.create(admission_fee_paid: true) }
      redirect_to print_tickets_tickets_path(ticket_ids: tickets.map(&:id))
    else
      render nothing: true
    end
  end

  def ticket_inspection
    @active = :ticket_inspection
    @no_header = true
  end

  def checkin
    if params[:ticket_code].blank? || (ticket = Ticket.find_by_code(params[:ticket_code])).blank?
      render json: { status: "ticket_not_found" }
    elsif ticket.checked_in?
      render json: { status: "ticket_already_checked_in" }
    else
      admission_fee_paid = ticket.admission_fee_paid?
      order = ticket.ticket_order.blank? ? nil : { id: ticket.ticket_order.id, remaining_admission_fee: ticket.ticket_order.tickets.where(admission_fee_paid: false).count * 3 }
      ticket.update_attribute :checked_in, true
      ticket.update_attribute :admission_fee_paid, true
      render json: { status: "checkin_successful", admission_fee_paid: admission_fee_paid, order: order }      
    end
  end

  protected
    def set_active_item
      @active = :tickets
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= simple_form_for(@ticket) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :code %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<%= form_tag print_tickets_tickets_path, method: "get" do %>
  <table class="table table-striped table-with-actions">
    <thead>
      <tr>
        <th>
          <%= submit_tag "Tickets drucken", class: "btn btn-primary btn-sm" %>
          <%= link_to "Alle Pforten-Tickets drucken",  print_tickets_tickets_path(ticket_ids: Ticket.where(ticket_order: nil).map(&:id)), class: "btn btn-warning btn-sm" %>
        </th>
        <th>Code</th>
        <th>Bestellung</th>
        <th>Eingecheckt?</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= check_box_tag 'ticket_ids[]', ticket.id %></td>
          <td><%= ticket.code %></td>
          <td><%= ticket.ticket_order.present? ? link_to("Bestellung", ticket.ticket_order) : "-" %></td>
          <td><%= format_tick ticket.checked_in? %></td>
          <td><%= destroy_button ticket %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<h2>Neue Tickets erstellen und drucken</h2>
<%= form_tag batch_create_tickets_path, method: "post" do %>
  <div class="form-group">
    Anzahl: <%= number_field_tag :amount, class: "form-control" %>
  </div>
  <%= submit_tag "Tickets erstellen", class: "btn btn-default" %>
<% end %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/print_tickets.html.erb
<h2>Tickets drucken</h2>
<% for ticket in @tickets %>
    <%= image_tag image_ticket_path(ticket), style: "max-width: 250px !important; page-break-inside: avoid; display: block; float: left; margin: 1em;" %>
<% end %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @ticket.code %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>