config/routes.rb
Rails.application.routes.draw do
  scope "/auth" do
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  end
  
  get '/login', to: redirect('auth/users/sign_in')
  get '/lpr' => 'home#landing_page_redirect'

  get 'v' => 'audience_votes#new', as: :new_audience_vote
  post 'v' => 'audience_votes#create', as: :create_audience_vote
  get 'v/thankyou' => 'audience_votes#thankyou', as: :audience_vote_thankyou

  get 'orders/new'
  post 'orders/create'
  get 'orders/confirm_email'
  get 'orders/print_tickets'
  get 'orders/thankyou'
  get 'orders/verify_email'

  get 'settings' => 'settings#modify'
  post 'settings' => 'settings#update', as: :update_settings

  get 'home/index'
  resources :participants do
    collection do
      post 'update_order'
    end
  end
  resources :ticket_orders do
    collection do
      post 'admission_fee_paid'
    end
  end
  resources :tickets, only: [:index, :destroy] do
    collection do
      get 'print_tickets'
      post 'batch_create'
      get 'ticket_inspection'
      post 'checkin'
    end
    member do
      get 'image'
    end
  end
  resources :votes, only: :index
  resources :jurors, only: [:create, :update, :destroy]

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket_order.rb
class TicketOrder < ApplicationRecord
    has_many :tickets, dependent: :destroy

    before_create :set_email_verification_token

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :number_of_tickets, presence: true
    validates :email, presence: true, format: { with: Devise.email_regexp }    

    def set_email_verification_token
        begin
            self.email_verification_token = SecureRandom.hex
        end while TicketOrder.find_by(email_verification_token: email_verification_token).present?
        true
    end
end

app/controllers/ticket_orders_controller.rb
class TicketOrdersController < ApplicationController
  load_and_authorize_resource
  
  # GET /ticket_orders
  # GET /ticket_orders.json
  def index
    @ticket_orders = TicketOrder.all
  end

  # GET /ticket_orders/1
  # GET /ticket_orders/1.json
  def show
  end

  # GET /ticket_orders/new
  def new
    @ticket_order = TicketOrder.new
  end

  # GET /ticket_orders/1/edit
  def edit
  end

  # POST /ticket_orders
  # POST /ticket_orders.json
  def create
    @ticket_order = TicketOrder.new(ticket_order_params)

    respond_to do |format|
      if @ticket_order.save
        format.html { redirect_to @ticket_order, notice: 'Ticket order was successfully created.' }
        format.json { render :show, status: :created, location: @ticket_order }
      else
        format.html { render :new }
        format.json { render json: @ticket_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_orders/1
  # PATCH/PUT /ticket_orders/1.json
  def update
    respond_to do |format|
      if @ticket_order.update(ticket_order_params)
        format.html { redirect_to @ticket_order, notice: 'Ticket order was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket_order }
      else
        format.html { render :edit }
        format.json { render json: @ticket_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_orders/1
  # DELETE /ticket_orders/1.json
  def destroy
    @ticket_order.destroy
    respond_to do |format|
      format.html { redirect_to ticket_orders_url, notice: 'Ticket order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def admission_fee_paid
    if (order = TicketOrder.find_by(id: params[:order_id])).present?
      order.tickets.update_all admission_fee_paid: true
    end
    render json: {status: 'success'}
  end

  protected
    def set_active_item
      @active = :ticket_orders
    end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_order_params
      params.require(:ticket_order).permit(:number_of_tickets, :email, :email_verified, :first_name, :last_name)
    end
end

app/helpers/ticket_orders_helper.rb
module TicketOrdersHelper
end

app/views/ticket_orders/_form.html.erb
<%= simple_form_for(@ticket_order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name, label: "Vorname" %>
    <%= f.input :last_name, label: "Nachname" %>
    <%= f.input :number_of_tickets, label: "Anzahl der Tickets" %>
    <%= f.input :email, label: "E-Mail-Adresse" %>
    <%= f.input :email_verified, label: "E-Mail-Adresse bestätigt" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Speichern" %>
  </div>
<% end %>

app/views/ticket_orders/edit.html.erb
<h2>Bestellung bearbeiten</h2>
<%= render 'form', ticket_order: @ticket_order %>

app/views/ticket_orders/index.html.erb
<table class="table table-striped table-with-actions">
  <thead>
    <tr>
      <th>Besteller(in)</th>
      <th>Ticketanzahl</th>
      <th>E-Mail</th>
      <th>E-Mail bestätigt/ Tickets versandt</th>
      <th>
        <%= new_button new_ticket_order_path %>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_orders.each do |ticket_order| %>
      <tr>
        <td><%= ticket_order.first_name %> <%= ticket_order.last_name %></td>
        <td><%= ticket_order.number_of_tickets %></td>
        <td><%= ticket_order.email %></td>
        <td><%= format_tick ticket_order.email_verified %></td>
        <td>
          <%= details_button ticket_order %>
          <%= edit_button edit_ticket_order_path(ticket_order) %>
          <%= destroy_button ticket_order %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ticket_orders/new.html.erb
<h2>Neue Bestellung</h2>
<%= render 'form', ticket_order: @ticket_order %>

app/views/ticket_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number of tickets:</strong>
  <%= @ticket_order.number_of_tickets %>
</p>

<p>
  <strong>Email:</strong>
  <%= @ticket_order.email %>
</p>

<p>
  <strong>Email verified:</strong>
  <%= @ticket_order.email_verified %>
</p>

<%= link_to 'Edit', edit_ticket_order_path(@ticket_order) %> |
<%= link_to 'Back', ticket_orders_path %>