config/routes.rb
Rails.application.routes.draw do
  scope "/auth" do
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  end
  
  get '/login', to: redirect('auth/users/sign_in')
  get '/lpr' => 'home#landing_page_redirect'

  get 'v' => 'audience_votes#new', as: :new_audience_vote
  post 'v' => 'audience_votes#create', as: :create_audience_vote
  get 'v/thankyou' => 'audience_votes#thankyou', as: :audience_vote_thankyou

  get 'orders/new'
  post 'orders/create'
  get 'orders/confirm_email'
  get 'orders/print_tickets'
  get 'orders/thankyou'
  get 'orders/verify_email'

  get 'settings' => 'settings#modify'
  post 'settings' => 'settings#update', as: :update_settings

  get 'home/index'
  resources :participants do
    collection do
      post 'update_order'
    end
  end
  resources :ticket_orders do
    collection do
      post 'admission_fee_paid'
    end
  end
  resources :tickets, only: [:index, :destroy] do
    collection do
      get 'print_tickets'
      post 'batch_create'
      get 'ticket_inspection'
      post 'checkin'
    end
    member do
      get 'image'
    end
  end
  resources :votes, only: :index
  resources :jurors, only: [:create, :update, :destroy]

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.erb
<% [:notice, :error, :alert].each do |level| %>
    <% unless flash[level].blank? %>
    	<div class="alert alert-<%= flash_class(level) %>" style="margin-bottom: 1em;">
    		<a class="close" data-dismiss="alert">×</a>
    		<%= content_tag :p, flash[level].html_safe %>
    	</div>
    <% end %>
<% end %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <div class="container">
    <h1>MSO hat Talent</h1>
    <ul class="nav nav-pills" style="margin-bottom: 1em;">
      <li role="presentation" class="<%= 'active' if @active == :home %>"><%= link_to 'Home', root_path %></li>
      <% if can? :manage, Participant %>
        <li role="presentation" class="<%= 'active' if @active == :participants %>"><%= link_to 'TeilnehmerInnen', participants_path %></li>
      <% end %>
      <% if can? :manage, Ticket %>
        <li role="presentation" class="<%= 'active' if @active == :tickets %>"><%= link_to 'Tickets', tickets_path %></li>
      <% end %>
      <li role="presentation" class="<%= 'active' if @active == :ticket_inspection %>"><%= link_to 'Ticketkontrolle', ticket_inspection_tickets_path, data: { turbolinks: false } %></li>
      <% if can? :manage, TicketOrder %>
        <li role="presentation" class="<%= 'active' if @active == :ticket_orders %>"><%= link_to 'Bestellungen', ticket_orders_path %></li>
      <% end %>
      <% if can? :manage, Vote %>
        <li role="presentation" class="<%= 'active' if @active == :votes %>"><%= link_to 'Stimmen', votes_path %></li>
      <% end %>
      <% if can? :manage, Settings %>
        <li role="presentation" class="<%= 'active' if @active == :settings %>"><%= link_to 'Einstellungen', settings_path %></li>
      <% end %>
      <li role="presentation"><%= link_to 'Abmelden', destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
<% else %>
  <nav class="navbar navbar-inverse" style="margin-bottom: 0;">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_url %>">
          MSO hat Talent
        </a>
      </div>
    </div>
  </nav>
<% end %>

app/views/layouts/_info_table.html.erb
<table class="table table-bordered">
    <tr>
        <td><%= glyphicon_with_text :flag, "Ort" %></td>
        <td>Aula der Marienschule Opladen</td>
    </tr>
    <tr>
        <td><%= glyphicon_with_text :calendar, "Datum" %></td>
        <td>01. Dezember 2017</td>
    </tr>
    <tr>
        <td><%= glyphicon_with_text :time, "Uhrzeit" %></td>
        <td>18.00 Uhr</td>
    </tr>
    <tr>
        <td><%= glyphicon_with_text :euro, "Preis pro Karte" %></td>
        <td>3€</td>
    </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>MSO hat Talent</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" unless @no_header %>
    <div class="container">
      <%= render "layouts/flash_messages" %>
      <div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>